# ----------------------------------------------------------
# 🧩 Build Angular app
# ----------------------------------------------------------
FROM node:22 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build --configuration production

# ----------------------------------------------------------
# 🚀 Serve Angular app with Nginx
# ----------------------------------------------------------
FROM nginx:latest
COPY --from=build /app/dist/empnew /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
